<?php
/**
 * @file
 * 
 * Main BPI module file
 * 
 */

define('BPI_PATH', drupal_get_path('module', 'bpi'));

/**
 * Implements hook_init
 */
function bpi_init() {
  drupal_add_js(BPI_PATH . '/js/dropdown/jquery.dd.js');
  drupal_add_js(BPI_PATH . '/js/bpi-scripts.js');
  drupal_add_css(BPI_PATH . '/css/dd.css');
  drupal_add_css(BPI_PATH . '/css/bpi-styles.css');
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'jquery.form');

  global $user;
  $shortcut_set = shortcut_set_load('shortcut-set-2');
  
  if (!$shortcut_set) {
    $shortcut_set = new stdClass();
    $shortcut_set->title = 'BPI';
    $shortcut_set->links = array(
      array(
        'link_path' => 'node/add',
        'link_title' => 'Add content',
        'weight' => -20,
      ),
      array(
        'link_path' => 'admin/content',
        'link_title' => 'Find content',
        'weight' => -19,
      ),
     /* array(
        'link_path' => 'admin/bpi',
        'link_title' => 'BPI',
        'weight' => -18,
      ),*/
    );
    
    shortcut_set_save($shortcut_set);
  }
  
  shortcut_set_assign_user($shortcut_set, $user);
}

/**
 * Implements hook_menu
 *
 * @return array
 *   An array with query responders
 */
function bpi_menu() {
  $items = array();

  // Updates page
  $items['admin/content/updates'] = array(
    'title' => 'Updates',
    'description' => 'Syndicated nodes which have been updated',
    'page callback' => 'bpi_updates',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '2',
  );

  // Syndicated nodes page
  $items['admin/content/syndicated'] = array(
    'title' => 'Syndicated',
    'description' => 'Nodes which you syndicated',
    'page callback' => 'bpi_syndicated_nodes',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '3',
  );

  // Channels page
  $items['admin/content/channels'] = array(
    'title' => 'Channels',
    'description' => 'Current available channels',
    'page callback' => 'bpi_channels',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '4',
  );

  // Favorites page
  $items['admin/content/favorites'] = array(
    'title' => 'Favorites',
    'description' => 'Favorites (channels, authors, etc.)',
    'page callback' => 'bpi_favorites',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '5',
  );

  // Search page
  $items['admin/content/search'] = array(
    'title' => 'Search',
    'description' => 'Search nodes from the well',
    'page callback' => 'bpi_search',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '6',
  );

  $items['admin/content/subscriptions'] = array(
    'title' => 'Subscriptions',
    'description' => 'Subscribe to variuos vategories of nodes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bpi_subscribe_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => '7',
  );
  
  $items['admin/content/ajax/node/%/invite'] = array(
    'title' => 'Channel invite',
    'description' => 'Invite other user to your channel',
    'page arguments' => array(2, 4),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
    'page callback' => 'bpi_ajax_channel_invite',
  );
  
  $items['admin/content/ajax/node/%/subscribed_users'] = array(
    'description' => 'List of subscribed users to this channel',
    'page arguments' => array(2, 4),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
    'page callback' => 'bpi_ajax_channel_subscribed_users',
  );

  return $items;
}

function bpi_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_admin_content') {
    // Cols and rows
    $header = $form['admin']['nodes']['#header'];
    $rows = $form['admin']['nodes']['#options'];

    // Add a custom col
    $header['rating'] = array(
      'data' => 'Add to Favorites',
    );

    // Add a custom data to row
    // Node ID required as array key
    $rows['5']['rating'] = theme('bpi_flag_dropdown');

    $form['admin']['nodes']['#header'] = $header;
    $form['admin']['nodes']['#options'] = $rows;
  }
}

/**
 * Implements hook_theme
 *
 * @return array
 *   Array of available themes
 */
function bpi_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['bpi_flag_dropdown'] = array(
    'variables' => array('vars' => NULL),
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_flag_dropdown',
  );
  
  $hooks['subscribed_users'] = array(
    'variables' => array(),
    'template' => 'templates/bpi_subscribed_users',
  );

  $hooks['bpi_syndicated_nodes_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_syndicated_nodes',
  );

  $hooks['bpi_channels_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_channels',
  );

  $hooks['bpi_favorites_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_favorites',
  );

  $hooks['bpi_updates_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_updates',
  );

  $hooks['bpi_search_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_search',
  );

  $hooks['well_node'] = array(
    'variables' => array(
      'title' => NULL,
      'description' => NULL,
      'read' => NULL,
      'rating' => NULL,
      'rated' => NULL,
      'date' => NULL,
      'author' => NULL,
      'category' => NULL,
      'syndicated' => NULL,
      'lix' => NULL, // @todo - how's that beeing translated ?!
      'library' => NULL,
      'channel' => NULL,
    ),
    'template' => 'templates/bpi_well_node',
  );

  $hooks['bpi_node_edit_form'] = array(
    'render element' => 'form',
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_edit_node',
  );

  $hooks['node_info'] = array(
    'variables' => array('node_id' => NULL),
    'path' => BPI_PATH . '/templates',
    'template' => 'bpi_edit_node_info'
  );

  return $hooks;
}

/**
 * 'Syndicated nodes' page callback
 *
 * @return array
 *   Page structure
 */
function bpi_syndicated_nodes() {
  $data = array();

  $data['grid_rows'] = array(
    array(
      '<a href="/node/1">Pa gensyn i Helsingor 2011</a> <span class="marker">updated</span>',
      'Article',
      '<a property="foaf:name" typeof="sioc:UserAccount" about="/user/1" xml:lang="" class="username" title="View user profile." href="/user/1">Birgitte Hansen</a>',
      'published',
      '01/04/2011 - 17:51',
      '04/05/2011 - 16:56',
      'Gladsaxe Bibliotek',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>',
      theme('bpi_flag_dropdown')),
    array(
      '<a href="/node/1">Easy Magazine 2010</a>',
      'Article',
      '<a property="foaf:name" typeof="sioc:UserAccount" about="/user/1" xml:lang="" class="username" title="View user profile." href="/user/1">Ulla Terkelsen</a>',
      'published',
      '02/15/2011 - 04:12',
      '04/05/2011 - 16:58',
      'Frederiksebrg Bibliotekerne',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>',
      theme('bpi_flag_dropdown')),
    array(
      '<a href="/node/1">Easy Screen pa Svendborg Bibliotek</a>',
      'Article',
      '<a property="foaf:name" typeof="sioc:UserAccount" about="/user/1" xml:lang="" class="username" title="View user profile." href="/user/1">Barack Obama</a>',
      'draft',
      '03/08/2011 - 14:34',
      '04/05/2011 - 14:34',
      'Washington Centralbibliotek',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>',
      theme('bpi_flag_dropdown')),
  );

  return drupal_get_form('bpi_syndicated_nodes_form', $data);
}

function bpi_syndicated_nodes_form($form = array(), &$form_state, $form_data = array()) {
  $form['sort_filter'] = array(
    '#type' => 'fieldset',
    '#title' => 'SHOW ONLY ITEMS WHERE',
  );

  $form['sort_filter']['status'] = array(
    '#type' => 'select',
    '#title' => 'status',
    '#options' => array(
        'any',
    ),
  );

  $form['sort_filter']['type'] = array(
    '#type' => 'select',
    '#title' => 'type',
    '#options' => array(
        'any',
    ),
  );

  $form['sort_filter']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Filter'
  );

  $form['update_filter'] = array(
    '#type' => 'fieldset',
    '#title' => 'UPDATE OPTIONS',
  );

  $form['update_filter']['action'] = array(
    '#type' => 'select',
    '#options' => array(
        'Delete selected content',
      ),
  );

  $form['update_filter']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Update'
  );
  
  $header = array(
    array('data' => t('Title'), 'field' => 'node_title'),
    array('data' => t('Type'), 'field' => 'node_type'),
    t('Author'),
    array('data' => t('Status'), 'field' => 'node_status'),
    array('data' => t('Updated'), 'field' => 'node_updated', 'sort' => 'desc'),
    array('data' => t('Syndicated'), 'field' => 'node_syndicated'),
    array('data' => t('Library'), 'field' => 'node_library'),
    t('Operations'),
    'Add to Favorites'
  );

  $form['grid'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $form_data['grid_rows'],
  );

  return $form;
}

/**
 * 'Channels' page callback
 *
 * @return array
 *   Page structure
 */
function bpi_channels() {
  $data = array();

  $data['grid_rows'] = array(
    array(
      'My Channel A<br />' . l('Invite', 'admin/content/ajax/node/1/invite', array('attributes' => array('class' => array('use-ajax')))),
      '10<br /><a href="/admin/content">view nodes</a>',
      '0',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>'
    ),
    array(
      'Syndicated channel',
      '5<br /><a href="/admin/bpi/search">view nodes</a>',
      '7<br />'.l('see users', 'admin/bpi/ajax/node/1/subscribed_users', array('attributes' => array('class' => array('use-ajax')))),
      '<ul class="links inline"><li class="edit first"><a href="#" onclick="confirm(\'Are you sure?\');">unsubscribe</a></li></ul>'
    ),
    array(
      'My Channel B<br />' . l('Invite', 'admin/content/ajax/node/1/invite', array('attributes' => array('class' => array('use-ajax')))),
      '10<br /><a href="/admin/content">view nodes</a>',
      '4<br />' . l('see users', 'admin/bpi/ajax/node/1/subscribed_users', array('attributes' => array('class' => array('use-ajax')))),
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>'
    ),
  );

  return drupal_get_form('bpi_channels_form', $data);
}

function bpi_channels_form($form = array(), &$form_state, $form_data = array()) {
  $header = array(
    t('Name'),
    t('Nodes'),
    t('Subscbed users'),
    t('Operations')
  );

  $form['grid'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $form_data['grid_rows'],
  );

  return $form;
}

function bpi_channels_invite_form($form = array(), &$form_state, $form_data = array()) {
  $form['name'] = array(
    '#type' => 'textfield',
    '#name' => 'name',
    '#title' => 'Enter name'
  );

  $form['invite'] = array(
    '#type' => 'button',
    '#value' => 'Invite',
    '#ajax' => array(
      'callback' => 'bpi_ajax_channel_invite_close'
    )
  );

  $form['close'] = array(
    '#type' => 'button',
    '#value' => 'Close',
    '#ajax' => array(
      'callback' => 'bpi_ajax_channel_invite_close'
    )
  );

  return $form;
}

/**
 * Ajax callback method, preparing commands for invite popup
 * 
 * @param string $type
 * @param integer $channel_id
 */
function bpi_ajax_channel_invite($type = 'ajax', $channel_id = 0) {
  if ($type == 'ajax') {
    if ($channel_id != 0) {
      $commands = array();

      $commands[] = ajax_command_ding_popup(
        'invite_form',
        'Invite to channel',
        drupal_render(drupal_get_form('bpi_channels_invite_form')));

      ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
    }
  }
}

/**
 * Ajax callback method to close invite form
 */
function bpi_ajax_channel_invite_close() {
		return array('#type' => 'ajax', '#commands' => array(ajax_command_ding_popup_close('invite_form')));
}

/**
 * Ajax callback method, preparing commands for subscribed users popup
 * 
 * @param string $type
 * @param integer $channel_id
 */
function bpi_ajax_channel_subscribed_users($type, $channel_id) {
  if ($channel_id != 0) {
      $commands = array();

      $commands[] = ajax_command_ding_popup(
        'invite_form',
        'Subscribed users',
        theme('subscribed_users'));

      ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
    }
}

/**
 * 'Favorites' page callback
 *
 * @return array
 *   Page structure
 */
function bpi_favorites() {
  $data = array();

  $data['rows'] = array(
     array(
      '<img src="'.BPI_PATH.'/img/flag_green.jpg" width="16" height="16" alt="" />',
      '<a href="/node/1">Pa gensyn i Helsingor 2011</a>',
      'Article',
      '<a property="foaf:name" typeof="sioc:UserAccount" about="/user/1" xml:lang="" class="username" title="View user profile." href="/user/1">Birgitte Hansen</a>',
      'published',
      '04/09/2011 - 14:07',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>',
    ),
    array(
      '<img src="'.BPI_PATH.'/img/flag_yellow.jpg" width="16" height="16" alt="" />',
      '<a href="/node/1">Easy Magazine 2010</a>',
      'Article',
      '<a property="foaf:name" typeof="sioc:UserAccount" about="/user/1" xml:lang="" class="username" title="View user profile." href="/user/1">Ulla Terkelsen</a>',
      'published',
      '04/09/2011 - 14:23',
      '<ul class="links inline"><li class="edit first"><a href="/node/1/edit?destination=admin/content">edit</a></li>
<li class="delete last"><a href="/node/1/delete?destination=admin/content">delete</a></li>
</ul>',
    ),
  );

  return drupal_get_form('bpi_favorites_form', $data);
}

function bpi_favorites_form($form = array(), &$form_state, $form_data = array()) {
  $header = array(
    array('data' => ''),
    array('data' => 'title', 'field' => 'n.title'),
    'type',
    array('data' => 'author', 'field' => 'n.author'),
    'status',
    array('data' => 'updated', 'field' => 'n.updated'),
    'operations',
  );

  $form['grid'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $form_data['rows'],
  );

  $form['operations'] = array(
    '#type' => 'select',
    '#options' => array('Delete'),
    '#title' => 'With selected: ',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

/**
 * 'Updates' page callback
 *
 * @return array
 *   Page structure
 */
function bpi_updates() {
  return theme('updates');
}

/**
 * 'Search' page callback
 *
 * @return array
 *   Page structure
 */
function bpi_search() {
  $data = array();

  return drupal_get_form('bpi_search_form', $data);
}

function bpi_search_form($form = array(), &$form_state, $form_data = array()) {

  $form['search'] = array(
    '#type' => 'textfield',
    '#title' => 'Search for: ',
    '#required' => TRUE,
    '#prefix' => '<div id="search_form">',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#suffix' => '</div>'
  );

  $form['type'] = array(
    '#type' => 'fieldset',
    '#title' => 'TYPE',
    '#prefix' => '<div id="bpi_search_filter">',
  );

  $form['type']['article'] = array(
    '#type' => 'checkbox',
    '#title' => 'Article'
  );

  $form['type']['event'] = array(
    '#type' => 'checkbox',
    '#title' => 'Event'
  );

  $form['type']['review'] = array(
    '#type' => 'checkbox',
    '#title' => 'Review'
  );

  $form['group'] = array(
    '#type' => 'fieldset',
    '#title' => 'TARGET GROUP',
    '#suffix' => '</div>'
  );

  $form['group']['adults'] = array(
    '#type' => 'checkbox',
    '#title' => 'Adults'
  );

  $form['group']['born'] = array(
    '#type' => 'checkbox',
    '#title' => 'Born' // @todo - translate 'Born'
  );

  $form['group']['young'] = array(
    '#type' => 'checkbox',
    '#title' => 'Young'
  );

  return $form;
}

function bpi_well_nodes() {
  $nodes = array();

  // @todo
  // Test purpose data
  // Remove that after live retrieval
  $nodes[] = array(
    'title' => 'Sommerlukket',
    'description' => 'Tekstuddrag fra artikel Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem',
    'read' => FALSE, // @todo - needs translation (dk: laest)
    'rating' => 3,
    'rated' => 17,
    'date' => '13 marts 2011',
    'author' => 'Lisbeth Hollesen',
    'category' => 'Andet',
    'syndicated' => 4,
    'lix' => 56, // @todo - needs translation
    'library' => 'Albertslund',
    'channel' => 'Nu er det sommerferie'
  );

  $nodes[] = array(
    'title' => 'Tirsdagsgodter',
    'description' => 'Tekstuddrag fra artikel Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem',
    'read' => TRUE, // @todo - needs translation (dk: laest)
    'rating' => 3,
    'rated' => 12,
    'date' => '13 marts 2011',
    'author' => 'M. Christensen',
    'category' => 'Andet',
    'syndicated' => 2,
    'lix' => 21, // @todo - needs translation
    'library' => 'Hovedbiblioteket',
    'channel' => 'Slik'
  );

  $output = '';
  foreach($nodes as $v) {
    $output .= theme('well_node', $v);
  }

  return $output;
}


function bpi_node_edit($node_id) {
  // @todo
  // Here should be placed node retrieval routine
  // As for now it's a dummy data, remove after normal fetch

  $data = array(
      'id' => $node_id,
      'title' => 'Trololo',
      'teaser' => 'Lorem ipsum dolor sit amet consectetuer adispcing elit',
      'body' => 'As for 2039, a number of professional astronomers predicted that,
        Apophis asteroid, discovered in 2004, could change it\'s orbit in a way
        that it could cross the Earth\'s orbit. Although due to huge amount of gravity
        that Sun is creating, in such large timespan it\'s truly hard to predict how exactly
        the orbit of Apophis will lay through space. In case of direct hit, this 900
        meters rock, could produce an impact equalised to 2000 megatomb nuclear bomb with
        total destruction in range of 60 miles and produce blast wind with a velocity
        700 meters per second...',
      'operations' => array(
        'auto_update' => TRUE,
        'copy_images' => FALSE,
        'local_changes' => FALSE,
        'auto_publish' => FALSE,
        'auto_promote' => FALSE,
        'references_ting' => FALSE,
        'references_links' => FALSE,
        'syndication_changes' => FALSE,
        'view_syndication' => FALSE,
      ),
      'images' => array(),
  );

  //return drupal_get_form(bpi_node_edit_form, $data);
  return drupal_get_form('bpi_node_edit_form', $data);
}

function template_preprocess_bpi_node_edit_form(&$variables) {
  
}

function bpi_node_edit_form($form = array(), &$form_state, $form_data = array()) {
  $form['id'] = array(
    '#type' => 'hidden',
    '#value' => $form_data['id'],
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'Title',
    '#required' => TRUE,
    '#value' => (isset($form_data['title'])) ? $form_data['title'] : '',
  );

  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => 'Body',
    '#default_value' => (isset($form_data['body'])) ? $form_data['body'] : '',
  );

  $form['teaser'] = array(
    '#type' => 'textarea',
    '#title' => 'Teaser',
    '#default_value' => (isset($form_data['teaser'])) ? $form_data['teaser'] : '',
  );

  $form['auto_update'] = array(
    '#type' => 'checkbox',
    '#title' => 'Activate auto update?',
    '#default_value' => (
          isset($form_data['operations']['auto_update']) &&
          $form_data['operations']['auto_update'] == TRUE) ?
            1 : 0,
  );

  $form['copy_images'] = array(
    '#type' => 'checkbox',
    '#title' => 'Copy images?',
    '#default_value' => (
          isset($form_data['operations']['copy_images']) &&
          $form_data['operations']['copy_images'] == TRUE) ?
            1 : 0,
  );

  $form['local_changes'] = array(
    '#type' => 'checkbox',
    '#title' => 'Make changes locally?',
    '#default_value' => (
          isset($form_data['operations']['local_changes']) &&
          $form_data['operations']['local_changes'] == TRUE) ?
            1 : 0,
  );

  $form['auto_publish'] = array(
    '#type' => 'checkbox',
    '#title' => 'Auto publish locally?',
    '#default_value' => (
          isset($form_data['operations']['auto_publish']) &&
          $form_data['operations']['auto_publish'] == TRUE) ?
            1 : 0,
  );

  $form['auto_promote'] = array(
    '#type' => 'checkbox',
    '#title' => 'Auto promote to frontpage?',
    '#default_value' => (
          isset($form_data['operations']['auto_promote']) &&
          $form_data['operations']['auto_promote'] == TRUE) ?
            1 : 0,
  );

  $form['references_ting'] = array(
    '#type' => 'checkbox',
    '#title' => 'Remove references (TING)?',
    '#default_value' => (
          isset($form_data['operations']['references_ting']) &&
          $form_data['operations']['references_ting'] == TRUE) ?
            1 : 0,
  );

  $form['references_links'] = array(
    '#type' => 'checkbox',
    '#title' => 'Remove references (links)?',
    '#default_value' => (
          isset($form_data['operations']['references_links']) &&
          $form_data['operations']['references_links'] == TRUE) ?
            1 : 0,
  );

  $form['syndication_changes'] = array(
    '#type' => 'checkbox',
    '#title' => 'Make changes after syndication?',
    '#default_value' => (
          isset($form_data['operations']['syndication_changes']) &&
          $form_data['operations']['syndication_changes'] == TRUE) ?
            1 : 0,
  );

  $form['view_syndication'] = array(
    '#type' => 'checkbox',
    '#title' => 'View node after syndication?',
    '#default_value' => (
          isset($form_data['operations']['syndication_changes']) &&
          $form_data['operations']['view_syndication'] == TRUE) ?
            1 : 0,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit'
  );

  return $form;
}

function bpi_node_info($node_id = 0) {
  $data = array();

  if ($node_id > 0) {
    $data = array('node_info' => array(
        'pic_copy' => TRUE,
        'references' => TRUE,
        'author' => 'Birgitte Hansen',
        'library' => 'Gladsaxe Bibliotekerne',
        'created' => '04-05-2011 15:10',
        'category' => 'Sports',
        'target' => 'Adults',
        'channel' => array(
          'this_is_nice',
          'favoriteNodes'
        ),
        'lix' => 1823));
  }

  return $data;
}

function bpi_node_edit_form_submit($form = array(), &$form_state) {
  
}

function bpi_subscribe_form($form = array(), &$form_state) {
  

  $form['subscribe_audience'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Target audience:',
    '#options' => array(
      'Adults',
      'Seniors',
      'Children'
    ),
  );

  $form['subscribe_author'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Author:',
    '#options' => array(
      'Peter',
      'Jan',
      'Batman'
    ),
  );

  $form['subscribe_library'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Library:',
    '#options' => array(
      'Library A',
      'Library B',
      'Library C'
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}
